### ISSUE TITLE
Fix tests on Python 3.6

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsredshift#31]
https://travis-ci.org/HearthSim/hsredshift/jobs/240134181#L211

**Comment by jleclanche** [comment]
Wait, so the output is different on 3.4 and 3.6? :/

**Comment by beheh** [comment]
Looks like it!

**Comment by jleclanche** [comment]
Took me a while to figure out exactly what was going on.

Basically it has to do with the different sorting algorithms in Python 3.6. The entities accumulated into the `entity_state` table are added into a `set()` -- that set does not preserve entity ordering.
In Python 3.6, the different ordering routines are causing the resulting accumulated lines to be less efficiently packed and it ends up being 110 lines instead of 109.

Commit aea7a5b1df1a6e7544c9c98af1b62102199a0bd9 forces the iteration to happen in order of the entity IDs. This makes the whole thing more predictable and ensures that the entity state rows are added in order of entity IDs (which is probably a generally good idea).

When adding the sorted() call, I uncovered a couple of cases in the test where the set() contained LazyPlayer instances. This is a bad idea because LazyPlayer(2) != 2, so the accumulator may contain multiple instances of entities. This is fixed in f60ec6e3ea621800be42287682e192c3d57ce790 (I'm hoping I don't need to cast the rest -- we'll find out once this goes into prod).
