### ISSUE TITLE
Add timeframe for My Cards and Mulligan Guide to the query metadata

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hsredshift#39]
We need the timeframe in order to show it on HSReplay.net.
- [x] Mulligan Guide
- [ ] My Cards

**Comment by beheh** [comment]
This is going to be tricky in My Cards, since users specifically request a time frame before a query is loaded. We could write an extra query to determine eligibility I guess, but that's not in the metadata then. Alternatively we just add it to My Cards no matter what the user requests and then the frontend warns the user that it's not actually 7/14/30 days, but only X days.
